services:
  fuseki:
    image: ghcr.io/kurrawong/fuseki-geosparql:git-main-e642d849
    environment:
      - JAVA_OPTS=-Xms512m -Xmx2048m
    ports:
      - 3030:3030
    volumes:
      - fuseki-data:/fuseki
    profiles:
      - db
      - stack

  prez:
    image: ghcr.io/rdflib/prez:3.5.0
    ports:
      - 8000:8000
    environment:
      - SPARQL_ENDPOINT=http://fuseki:3030/bgs
    # depends_on:
    #   - fuseki
    healthcheck:
      test: ["CMD", "curl", "-f", "http://fuseki:3030"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 20s
    profiles:
      - prez
      - stack

  prez-ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5173:8000
    env_file: .env
    # Commenting below out due to bug in docker-compose: https://github.com/docker/compose/issues/10751
    # depends_on:
    #   - prez
    healthcheck:
      test: ["CMD", "curl", "-f", "http://prez:8000"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 30s
    profiles:
      - ui
      - stack

  prez-ui-dev:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 5173:5173
    volumes:
      - ./.env:/app/.env
      - ./components/App.vue:/app/src/App.vue
      - ./public/images:/app/public/images
      - ./public/favicon.ico:/app/public/favicon.ico
      - ./public/globals.css:/app/public/globals.css

volumes:
  fuseki-data:
